### ISSUE TITLE
The website is not responsive and efficient for mobile usage

### ISSUE THREAD

**Issue by Vishnuzdubey** [Aloneking789/elite#13]
If anyone interested to make the website responsive and efficient for mobile usage, he/she will be assigned level-3 for gssoc and hacktoberfest

**Comment by VBsaini** [comment]
HI, can you please explain in which pages do you need responsiveness as i can see its already responsive

**Comment by Aloneking789** [comment]
@VBsaini  Try opening the website on mobile the Navigation buttons are not visible(Ex- Home, Profile) which is visible in laptops or big screen 
![Screenshot_20241015-165015](https://github.com/user-attachments/assets/9af3414b-2e66-4df7-939f-541a0af6dae7)

**Comment by YuvamGupta** [comment]
Please assign me this issue

**Comment by Aloneking789** [comment]
@VBsaini if you want to contribute to this repo you can start working on project section where we can showcase our projects
please raise this issue I will assign it to you

**Comment by VBsaini** [comment]
Hi, i fixed the issue and made the website responsive with mobile how do i proceed further sorry its my first time contributing
