### ISSUE TITLE
Create Members Page instead of GitHub Page

### ISSUE THREAD

**Issue by ag21o9** [Aloneking789/elite#9]
If anyone interested in creating a members page of the team portfolio, can be assigned to create it, 
the page will include all member's details in a tile form along with their GitHub ID, LinkedIn ID and work experience,

**Comment by Aloneking789** [comment]
yes if anyone is interested to make this pages I can provide you with the necessary details or you can add dummy text and we can edit it further

**Comment by VBsaini** [comment]
Hi, please assign this issue to me and also let me know if you have any design templates in mind
